require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe PapersController do

  def mock_paper(stubs={})
    @mock_paper ||= mock_model(Paper, stubs).as_null_object
  end


  describe "paper functions" do
    before(:each) do
      @paper = Factory(:paper)
      @paper.lookup_info
      @user = Factory(:user, :email => Factory.next(:email))
      @group = Factory(:group)
      @group.add(@user)
      test_sign_in(@user)
    end
  

    describe "GET show" do
      it "assigns the requested paper as @paper" do
        get :show, :id => @paper.id
        assigns(:paper).should == @paper
      end

    end

    describe "pubmed id lookup" do
   
      it "should look up an existing paper" do
        get :lookup, :search => @paper.pubmed_id.to_s
        response.should redirect_to(@paper)
      end
    end

    describe "show from mail" do
       
       before(:each) do
          @maillog = Maillog.create!(:user => @user, :about => @paper, :purpose => 'comment_response')
       end

       it "should mark a conversion if the paper matches" do
          get :show_from_mail, :id => @paper.id, :m_id => @maillog.id
          Maillog.find(@maillog.id).conversiona.should_not be nil
          response.should redirect_to(@paper)
       end

       it "should not mark a conversion if the paper does not match" do
          @paper2 = Factory(:paper, :pubmed_id => '7809879')
          get :show_from_mail, :id => @paper2.id, :m_id => @maillog.id
          @maillog.conversiona.should be nil
          response.should redirect_to(@paper2)
       end
    end
  end
end
